# PowerScope Configuration

# Data sources
data:
  iso:
    # ISO local CSV data configuration
    source_path: "data/raw/iso_data/"
    
  weather:
    # Weather data from Meteostat
    api_key: ""
    locations: []

# Model configuration
models:
  lightgbm:
    # LightGBM quantile regression parameters
    n_estimators: 100
    learning_rate: 0.1
    max_depth: 6
    
  torch:
    # PyTorch model parameters
    hidden_size: 128
    num_layers: 2
    dropout: 0.2

# Training configuration
training:
  test_size: 0.2
  validation_size: 0.2
  random_state: 42

# Forecasting
forecast:
  quantiles: [0.1, 0.5, 0.9]  # P10, P50, P90
  horizon: 24  # hours ahead